// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSUSPedido.Helpers;

namespace WebSUSPedido.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210519115046_New1905")]
    partial class New1905
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebSUSPedido.Models.Login.OPE_USUARIO", b =>
                {
                    b.Property<string>("CODIGO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CODIGO_EMPRESA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOMBRE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REFERENCIA3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REFERENCIA35")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("REFERENCIA33")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("ESTADO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CODIGO");

                    b.ToTable("OPE_USUARIO");
                });

            modelBuilder.Entity("WebSUSPedido.Models.Login.OPE_USUARIO", b =>
                {
                    b.OwnsMany("WebSUSPedido.Models.Login.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("OPE_USUARIOCODIGO")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("OPE_USUARIOCODIGO");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("OPE_USUARIOCODIGO");
                        });

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
