using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp;
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebSUSPedido.Models;

namespace WebSUSPedido.Reports
{
    public class RCotizaciones
    {
        public static IWebHostEnvironment webHostEnvironment;
        public string webRootPath;
        public string contentRootPath;
        private int _maxColumn = 4;
        private Document _document;
        private PdfPTable _pdfPTable = new PdfPTable(4);
        private PdfPCell _pdfPCell;
        private iTextSharp.text.Font _fontStyle;
        private MemoryStream _memoryStream = new MemoryStream();
        private List<CotizacionV> _pedidocab = new List<CotizacionV>();
        private List<DCotizacionV> _pedidobody = new List<DCotizacionV>();
        private PdfPTable Table = new PdfPTable(1);
        private iTextSharp.text.Font smallfont = FontFactory.GetFont("Arial", 7f);
        private iTextSharp.text.Font largefont = FontFactory.GetFont("Arial", "16", false, 16f, 1, BaseColor.Black);
        private iTextSharp.text.Font mediumfont = FontFactory.GetFont("Arial", "11", false, 11f, 1, BaseColor.Black);
        private iTextSharp.text.Font mediumfontSN = FontFactory.GetFont("Arial", "11", false, 11f, 0, BaseColor.Black);
        private iTextSharp.text.Font letraChica = FontFactory.GetFont("Arial", "8", false, 8f, 0, BaseColor.Black);
        private iTextSharp.text.Font letraMuyChica = FontFactory.GetFont("Arial", "6", false, 6f, 0, BaseColor.Black);
        private iTextSharp.text.Font letraChicaN = FontFactory.GetFont("Arial", "8", false, 8f, 1, BaseColor.Black);
        private iTextSharp.text.Font smallnumericfont = FontFactory.GetFont("Arial", "6", true, 6f, 2, BaseColor.Black);
        private iTextSharp.text.Font smallfontBlack = FontFactory.GetFont("Arial Black", 7f);
        private PdfPTable TableTitulo = new PdfPTable(1);
        private PdfPTable TableCliente = new PdfPTable(4);
        private PdfPTable TableItem = new PdfPTable(10);
        private PdfPTable TableProducto = new PdfPTable(10);
        private PdfPTable TableSubTotal = new PdfPTable(10);
        private PdfPTable TableCondicion = new PdfPTable(10);
        private PdfPTable TableFirma = new PdfPTable(10);
        private PdfPTable TableVendedor = new PdfPTable(10);
        private PdfPTable TableClienteCab = new PdfPTable(20);

        public System.Drawing.Image byteArrayToImage(byte[] byteArrayIn) => System.Drawing.Image.FromStream((Stream)new MemoryStream(byteArrayIn));

        public byte[] Report(
          List<CotizacionV> pedido,
          List<DCotizacionV> Detpedido,
          List<ImgHeadFoot> ImhdFT)
        {
            this._document = new Document(PageSize.A4, 10f, 10f, 20f, 30f);
            PdfWriter.GetInstance(_document, _memoryStream);
            //PdfWriter.GetInstance(this._document, (Stream)this._memoryStream).PageEvent = (IPdfPageEvent)new RCotizaciones.itsEvents(ImhdFT);
            this._document.Open();
            this.ReportHeader(pedido);
            this.ReporBody(Detpedido);
            this._pdfPTable.HeaderRows = 2;
            this._document.Add((IElement)this._pdfPTable);
            this._document.Close();
            return this._memoryStream.ToArray();
        }
        private void ReportHeader(List<CotizacionV> cbpedido)
        {
            this._pedidocab = cbpedido;
            this._pdfPCell = new PdfPCell(new Phrase("", this.mediumfontSN));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableTitulo.AddCell(this._pdfPCell);
            foreach (CotizacionV cotizacionV in this._pedidocab)
            {
                this._pdfPCell = new PdfPCell(new Phrase("    ", this.mediumfontSN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableTitulo.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("COTIZACION: " + cotizacionV.NUMERO_COTIZACION, this.largefont));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this._pdfPCell.Border = 0;
                this.TableTitulo.AddCell(this._pdfPCell);
                DateTime dateTime = cotizacionV.FECHA_COTIZACION;
                string str1 = dateTime.ToString("dd/mm/yyyy HH:MM");
                dateTime = DateTime.Now;
                string str2 = dateTime.ToString("dd/mm/yyyy");
                this._pdfPCell = new PdfPCell(new Phrase("Fecha de Emisión: " + str1 + " / Fecha de Creación: " + str2, this.mediumfontSN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableTitulo.AddCell(this._pdfPCell);
                this._document.Add((IElement)this.TableTitulo);
                this._pdfPCell = new PdfPCell(new Phrase("Cliente:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 2;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableClienteCab.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.PERSONA, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 18;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableClienteCab.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Dirección:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 2;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableClienteCab.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.DIRECCION, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 18;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableClienteCab.AddCell(this._pdfPCell);
                this._document.Add((IElement)this.TableClienteCab);
                this._pdfPCell = new PdfPCell(new Phrase("RUC: ", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.RUC, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Teléfono(s): ", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.TELEFONO, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Motivo: ", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("VENTA", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Lugar entrega: ", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.LUGAR_ENTREGA, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("O/C", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Sucursal: ", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                string str3 = " ";
                this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Estimados Señores: " + str3, this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 4;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCliente.AddCell(this._pdfPCell);
                this.TableItem.SpacingAfter = 10f;
                this._document.Add((IElement)this.TableCliente);
            }
        }
        private void ReporBody(List<DCotizacionV> detpedido)
        {
            this._pdfPCell = new PdfPCell(new Phrase("ITEM", this.letraChicaN));
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableItem.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase("DESCRIPCION", this.letraChicaN));
            this._pdfPCell.Colspan = 6;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableItem.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase("CANT.", this.letraChicaN));
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableItem.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase("V. UNIT", this.letraChicaN));
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableItem.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase("V. VENTA", this.letraChicaN));
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 1;
            this.TableItem.AddCell(this._pdfPCell);
            this.TableItem.SpacingAfter = 10f;
            this._document.Add((IElement)this.TableItem);
            this._pedidobody = detpedido;
            foreach (DCotizacionV dcotizacionV in this._pedidobody)
            {
                this._pdfPCell = new PdfPCell(new Phrase(dcotizacionV.SECUENCIA.ToString(), this.letraChicaN));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableProducto.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(dcotizacionV.NOMBRE, this.letraChicaN));
                this._pdfPCell.Colspan = 6;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableProducto.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(dcotizacionV.CANTIDAD.ToString(), this.letraChicaN));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableProducto.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(dcotizacionV.PRECIO.ToString("N2"), this.letraChicaN));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableProducto.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(dcotizacionV.IMPORTE.ToString("N2"), this.letraChicaN));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableProducto.AddCell(this._pdfPCell);
            }
            this._document.Add((IElement)this.TableProducto);
            foreach (CotizacionV cotizacionV in this._pedidocab)
            {
                DateTime dateTime = cotizacionV.FECHA_COTIZACION;
                dateTime = dateTime.AddDays(2.0);
                string str = dateTime.ToString("dd/MM/yyyy");
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 10;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 8;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Subtotal:", this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableSubTotal.AddCell(this._pdfPCell);
                double num = cotizacionV.IMPORTE_STOT;
                this._pdfPCell = new PdfPCell(new Phrase(num.ToString("N2"), this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 2;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 8;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Descuento:", this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableSubTotal.AddCell(this._pdfPCell);
                num = cotizacionV.IMPORTE_DESCUENTO;
                this._pdfPCell = new PdfPCell(new Phrase(num.ToString("N2"), this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 2;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 8;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("V.Venta:", this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableSubTotal.AddCell(this._pdfPCell);
                num = cotizacionV.VALOR_VENTA;
                this._pdfPCell = new PdfPCell(new Phrase(num.ToString("N2"), this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 2;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 8;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("IGV:18 %", this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableSubTotal.AddCell(this._pdfPCell);
                num = cotizacionV.IMPORTE_IGV;
                this._pdfPCell = new PdfPCell(new Phrase(num.ToString("N2"), this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 2;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 8;
                this._pdfPCell.HorizontalAlignment = 1;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("Total " + cotizacionV.MON, this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableSubTotal.AddCell(this._pdfPCell);
                num = cotizacionV.IMPORTE_TOTAL;
                this._pdfPCell = new PdfPCell(new Phrase(num.ToString("N2"), this.letraChica));
                this._pdfPCell.Colspan = 1;
                this._pdfPCell.HorizontalAlignment = 2;
                this.TableSubTotal.AddCell(this._pdfPCell);
                this.TableSubTotal.SpacingAfter = 10f;
                this._document.Add((IElement)this.TableSubTotal);
                this._pdfPCell = new PdfPCell(new Phrase("SON: DOS MIL SOLES CON 00 EXACTOS", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 10;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("CONDICIONES COMERCIALES:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 10;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("MONEDA:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.NOM_MONEDA, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("LUGAR DE ENTREGA:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(cotizacionV.LUGAR_ENTREGA, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("PLAZO DE ENTREGA:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase(str, this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("FORMA DE PAGO:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("CONTADO DEPOSITO", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("VALIDEZ DE LA OFERTA:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("2  DIAS", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("OBSERVACIONES:", this.letraChicaN));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 3;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
                this._pdfPCell = new PdfPCell(new Phrase("", this.letraChica));
                this._pdfPCell.Border = 0;
                this._pdfPCell.Colspan = 7;
                this._pdfPCell.HorizontalAlignment = 0;
                this.TableCondicion.AddCell(this._pdfPCell);
            }
            this._document.Add((IElement)this.TableCondicion);
            this.TableVendedor.SpacingBefore = 20f;
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 10;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 10;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChicaN));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 10;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase("   ", this.letraChica));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 10;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 10;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._pdfPCell = new PdfPCell(new Phrase(" ", this.letraChica));
            this._pdfPCell.Border = 0;
            this._pdfPCell.Colspan = 1;
            this._pdfPCell.HorizontalAlignment = 0;
            this.TableVendedor.AddCell(this._pdfPCell);
            this._document.Add((IElement)this.TableVendedor);
        }

        //public class itsEvents : PdfPageEventHelper
        //{
        //    private List<ImgHeadFoot> imghdft;

        //    public itsEvents(List<ImgHeadFoot> imgbyte)
        //    {
        //    }

        //    public override void OnStartPage(PdfWriter writer, Document document)
        //    {
        //        List<ImgHeadFoot> imghdft = this.imghdft;
        //        iTextSharp.text.Image instance = iTextSharp.text.Image.GetInstance("~/Images/Logogrouptito.png");
        //        instance.SetAbsolutePosition(10f, 750f);
        //        instance.ScaleAbsoluteWidth(80f);
        //        instance.ScaleAbsoluteHeight(80f);
        //        PdfPTable pdfPtable = new PdfPTable(1);
        //        pdfPtable.WidthPercentage = 100f;
        //        float[] relativeWidths = new float[1] { 10f };
        //        pdfPtable.SetWidths(relativeWidths);
        //        PdfPCell cell = new PdfPCell(instance);
        //        cell.Border = 0;
        //        cell.VerticalAlignment = 4;
        //        cell.HorizontalAlignment = 0;
        //        pdfPtable.AddCell(cell);
        //        document.Add((IElement)pdfPtable);
        //    }

        //    public override void OnEndPage(PdfWriter writer, Document document)
        //    {
        //        iTextSharp.text.Image instance = iTextSharp.text.Image.GetInstance("~/Images/Logogrouptito.png");
        //        instance.SetAbsolutePosition(0.0f, 0.0f);
        //        instance.ScaleAbsoluteWidth(450f);
        //        instance.ScaleAbsoluteHeight(100f);
        //        PdfPTable pdfPtable = new PdfPTable(1);
        //        pdfPtable.WidthPercentage = 100f;
        //        float[] relativeWidths = new float[1] { 10f };
        //        pdfPtable.SetWidths(relativeWidths);
        //        PdfPCell cell = new PdfPCell(instance);
        //        cell.Border = 0;
        //        cell.HorizontalAlignment = 0;
        //        pdfPtable.AddCell(cell);
        //        document.Add((IElement)pdfPtable);
        //    }
        //}
    }
}
